import os
from datetime import datetime
from typing import Dict, Literal

from dotenv import load_dotenv

from langchain_core.messages import AIMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_nvidia_ai_endpoints import ChatNVIDIA

from langgraph.graph import StateGraph, END, MessagesState


# ============================================================
# 1. ENVIRONMENT
# ============================================================

load_dotenv()

NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")
LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY")

if not NVIDIA_API_KEY:
    raise ValueError("NVIDIA_API_KEY is missing from .env")

if not LANGCHAIN_API_KEY:
    print("Warning: LANGCHAIN_API_KEY not found. LangSmith tracing may not work.")

os.environ["NVIDIA_API_KEY"] = NVIDIA_API_KEY

if LANGCHAIN_API_KEY:
    os.environ["LANGSMITH_API_KEY"] = LANGCHAIN_API_KEY

os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGSMITH_PROJECT"] = "Multi-AI_Agent"


# ============================================================
# 2. LLM
# ============================================================

llm = ChatNVIDIA(
    model="nvidia/nemotron-3-super-120b-a12b"
)


# ============================================================
# 3. STATE
# ============================================================

class SupervisorState(MessagesState):
    """
    Shared state used by all agents.

    original_task:
        The ORIGINAL user request.
        This should NEVER be replaced by agent messages.

    research_data:
        Output generated by Researcher.

    analysis:
        Output generated by Analyst.

    final_report:
        Output generated by Writer.

    next_agent:
        Agent selected by Supervisor.

    task_complete:
        Whether the complete workflow has finished.
    """

    original_task: str
    research_data: str
    analysis: str
    final_report: str
    next_agent: str
    task_complete: bool


# ============================================================
# 4. SUPERVISOR PROMPT
# ============================================================

def create_supervisor_chain():

    supervisor_prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """
You are the supervisor of a multi-agent AI research system.

You manage three agents:

1. researcher
   - Collects information related to the user's original request.

2. analyst
   - Analyzes the research findings and extracts insights.

3. writer
   - Creates the final report answering the original user request.

Your job is ONLY to decide which agent should work next.

Workflow:

If there is no research:
    researcher

If research exists but analysis does not:
    analyst

If research and analysis exist but final report does not:
    writer

If final report exists:
    DONE

IMPORTANT:
- Always use the ORIGINAL USER TASK.
- Do not interpret agent messages as the user's task.
- Respond with ONLY ONE of:
  researcher
  analyst
  writer
  DONE

Current state:

Has research: {has_research}

Has analysis: {has_analysis}

Has final report: {has_report}

Original user task:
{task}
"""
        ),
        (
            "human",
            "Decide the next agent."
        )
    ])

    return supervisor_prompt | llm


# ============================================================
# 5. SUPERVISOR AGENT
# ============================================================

def supervisor_agent(state: SupervisorState) -> Dict:

    # IMPORTANT:
    # Never use messages[-1] as the original task.
    task = state.get("original_task", "").strip()

    if not task:
        return {
            "messages": [
                AIMessage(
                    content="❌ Supervisor: No original user task was provided."
                )
            ],
            "next_agent": "end",
            "task_complete": True
        }

    has_research = bool(
        state.get("research_data", "").strip()
    )

    has_analysis = bool(
        state.get("analysis", "").strip()
    )

    has_report = bool(
        state.get("final_report", "").strip()
    )

    chain = create_supervisor_chain()

    decision = chain.invoke({
        "task": task,
        "has_research": has_research,
        "has_analysis": has_analysis,
        "has_report": has_report
    })

    decision_text = decision.content.strip().lower()

    print("\n" + "=" * 60)
    print("SUPERVISOR DECISION:", decision_text)
    print("=" * 60)

    # Exact matching is safer than:
    # "researcher" in decision_text

    if decision_text == "done":

        next_agent = "end"

        supervisor_msg = (
            "✅ Supervisor: All tasks are complete."
        )

    elif decision_text == "researcher":

        next_agent = "researcher"

        supervisor_msg = (
            "📋 Supervisor: Starting research..."
        )

    elif decision_text == "analyst":

        next_agent = "analyst"

        supervisor_msg = (
            "📋 Supervisor: Research complete. "
            "Starting analysis..."
        )

    elif decision_text == "writer":

        next_agent = "writer"

        supervisor_msg = (
            "📋 Supervisor: Analysis complete. "
            "Starting final report..."
        )

    else:

        # Fallback based on actual state
        if not has_research:
            next_agent = "researcher"

        elif not has_analysis:
            next_agent = "analyst"

        elif not has_report:
            next_agent = "writer"

        else:
            next_agent = "end"

        supervisor_msg = (
            f"⚠️ Supervisor returned unexpected decision: "
            f"{decision_text}. Using state-based routing."
        )

    return {
        "messages": [
            AIMessage(content=supervisor_msg)
        ],
        "next_agent": next_agent
    }


# ============================================================
# 6. RESEARCHER AGENT
# ============================================================

def researcher_agent(state: SupervisorState) -> Dict:

    # ALWAYS use original_task
    task = state.get("original_task", "").strip()

    if not task:
        return {
            "messages": [
                AIMessage(
                    content="❌ Researcher: No research task provided."
                )
            ],
            "research_data": ""
        }

    research_prompt = f"""
You are the Researcher in a multi-agent AI system.

Your job is to research the ORIGINAL USER REQUEST.

ORIGINAL USER REQUEST:
{task}

Provide useful research directly related to that request.

Include where relevant:

1. Key facts and background
2. Important concepts
3. Current trends or developments
4. Relevant statistics or quantitative information
5. Examples or case studies
6. Advantages and disadvantages
7. Important risks or limitations
8. Relevant recommendations
9. Sources or references when you know them

IMPORTANT RULES:

- Stay focused on the original user request.
- Do not change the research topic.
- Do not analyze the wording of the request.
- Do not talk about the multi-agent system.
- Do not say the user failed to provide a topic unless the
  original request genuinely contains no topic.
- Do not invent specific statistics or sources.
- Clearly distinguish known facts from uncertainty.
"""

    print("\n" + "=" * 60)
    print("RESEARCHER STARTED")
    print("=" * 60)

    research_response = llm.invoke([
        HumanMessage(content=research_prompt)
    ])

    research_data = research_response.content

    agent_message = (
        f"🔍 Researcher: Research completed for:\n"
        f"'{task}'\n\n"
        f"Research collected successfully."
    )

    print("\nResearch completed.")

    return {
        "messages": [
            AIMessage(content=agent_message)
        ],
        "research_data": research_data,
        "next_agent": "supervisor"
    }


# ============================================================
# 7. ANALYST AGENT
# ============================================================

def analyst_agent(state: SupervisorState) -> Dict:

    task = state.get("original_task", "").strip()

    research_data = state.get(
        "research_data",
        ""
    ).strip()

    if not task:
        return {
            "messages": [
                AIMessage(
                    content="❌ Analyst: Original task is missing."
                )
            ],
            "analysis": ""
        }

    if not research_data:
        return {
            "messages": [
                AIMessage(
                    content="❌ Analyst: Research data is missing."
                )
            ],
            "analysis": ""
        }

    analysis_prompt = f"""
You are the Analyst in a multi-agent AI system.

Your job is to analyze research in relation to the ORIGINAL USER REQUEST.

ORIGINAL USER REQUEST:
{task}

RESEARCH DATA:
{research_data}

Provide:

1. Key insights and patterns
2. Important findings
3. Strategic implications
4. Risks
5. Opportunities
6. Comparisons where relevant
7. Practical recommendations
8. Limitations or uncertainty in the research

IMPORTANT:

- Stay directly focused on the original user request.
- Do not replace the original topic.
- Do not analyze the researcher/agent communication.
- Do not discuss internal agent workflow.
- Do not invent facts that are not supported by the research.
- If the research is insufficient, clearly identify what is missing.
"""

    print("\n" + "=" * 60)
    print("ANALYST STARTED")
    print("=" * 60)

    analysis_response = llm.invoke([
        HumanMessage(content=analysis_prompt)
    ])

    analysis = analysis_response.content

    agent_message = (
        f"📊 Analyst: Analysis completed for:\n"
        f"'{task}'"
    )

    print("\nAnalysis completed.")

    return {
        "messages": [
            AIMessage(content=agent_message)
        ],
        "analysis": analysis,
        "next_agent": "supervisor"
    }


# ============================================================
# 8. WRITER AGENT
# ============================================================

def writer_agent(state: SupervisorState) -> Dict:

    task = state.get("original_task", "").strip()

    research_data = state.get(
        "research_data",
        ""
    ).strip()

    analysis = state.get(
        "analysis",
        ""
    ).strip()

    if not task:
        return {
            "messages": [
                AIMessage(
                    content="❌ Writer: Original task is missing."
                )
            ],
            "final_report": "",
            "task_complete": False
        }

    if not analysis:
        return {
            "messages": [
                AIMessage(
                    content="❌ Writer: Analysis is missing."
                )
            ],
            "final_report": "",
            "task_complete": False
        }

    writing_prompt = f"""
You are the final Writer in a multi-agent AI system.

Your job is to create a high-quality final answer to the ORIGINAL
USER REQUEST.

ORIGINAL USER REQUEST:
{task}

RESEARCH FINDINGS:
{research_data}

ANALYST FINDINGS:
{analysis}

Create a professional, useful and directly relevant final report.

Suggested structure:

1. Executive Summary
2. Key Findings
3. Analysis & Insights
4. Recommendations
5. Risks / Limitations
6. Conclusion

IMPORTANT RULES:

- The ORIGINAL USER REQUEST is the authoritative topic.
- Answer the original request directly.
- Never replace the topic with an agent message.
- Never analyze the words "Researcher", "Analyst", or "Supervisor".
- Do not mention the internal multi-agent workflow.
- Do not invent research.
- Do not invent statistics.
- Do not invent sources.
- If evidence is insufficient, say so clearly.
- Keep the report professional and readable.
"""

    print("\n" + "=" * 60)
    print("WRITER STARTED")
    print("=" * 60)

    report_response = llm.invoke([
        HumanMessage(content=writing_prompt)
    ])

    report = report_response.content

    final_report = f"""
📄 FINAL REPORT
{'=' * 60}

Generated:
{datetime.now().strftime('%Y-%m-%d %H:%M')}

Topic:
{task}

{'=' * 60}

{report}

{'=' * 60}

Report compiled by Multi-Agent AI System
Powered by NVIDIA Nemotron
"""

    print("\nFinal report generated.")

    return {
        "messages": [
            AIMessage(
                content="✍️ Writer: Report complete!"
            )
        ],
        "final_report": final_report,
        "next_agent": "end",
        "task_complete": True
    }


# ============================================================
# 9. ROUTER
# ============================================================

def router(
    state: SupervisorState
) -> Literal[
    "supervisor",
    "researcher",
    "analyst",
    "writer",
    "__end__"
]:

    next_agent = state.get(
        "next_agent",
        "supervisor"
    )

    task_complete = state.get(
        "task_complete",
        False
    )

    if task_complete:
        return END

    if next_agent == "end":
        return END

    if next_agent == "supervisor":
        return "supervisor"

    if next_agent == "researcher":
        return "researcher"

    if next_agent == "analyst":
        return "analyst"

    if next_agent == "writer":
        return "writer"

    return "supervisor"


# ============================================================
# 10. BUILD LANGGRAPH WORKFLOW
# ============================================================

workflow = StateGraph(SupervisorState)

# Add agents
workflow.add_node(
    "supervisor",
    supervisor_agent
)

workflow.add_node(
    "researcher",
    researcher_agent
)

workflow.add_node(
    "analyst",
    analyst_agent
)

workflow.add_node(
    "writer",
    writer_agent
)

# Entry point
workflow.set_entry_point(
    "supervisor"
)

# Conditional routing
for node in [
    "supervisor",
    "researcher",
    "analyst",
    "writer"
]:

    workflow.add_conditional_edges(
        node,
        router,
        {
            "supervisor": "supervisor",
            "researcher": "researcher",
            "analyst": "analyst",
            "writer": "writer",
            END: END
        }
    )


# Compile graph
graph = workflow.compile()


# ============================================================
# 11. RUN FUNCTION
# ============================================================

def run_agent(user_query: str):

    """
    Run the complete multi-agent workflow.
    """

    user_query = user_query.strip()

    if not user_query:
        raise ValueError(
            "User query cannot be empty."
        )

    print("\n")
    print("=" * 70)
    print("MULTI-AGENT AI SYSTEM")
    print("=" * 70)

    print("\nUSER REQUEST:")
    print(user_query)

    print("\nStarting workflow...")

    initial_state = {
        "messages": [
            HumanMessage(
                content=user_query
            )
        ],

        # ==================================================
        # CRITICAL FIX
        # ==================================================
        # Store the original user request separately.
        # It will NEVER be replaced by agent messages.
        "original_task": user_query,

        "research_data": "",
        "analysis": "",
        "final_report": "",
        "next_agent": "supervisor",
        "task_complete": False
    }

    result = graph.invoke(
        initial_state
    )

    print("\n")
    print("=" * 70)
    print("WORKFLOW COMPLETE")
    print("=" * 70)

    return result


# ============================================================
# 12. CLI
# ============================================================

if __name__ == "__main__":

    print("\nMulti-Agent AI Research System")
    print("Type 'exit' to quit.\n")

    while True:

        user_query = input(
            "You: "
        ).strip()

        if user_query.lower() in [
            "exit",
            "quit"
        ]:
            print("Goodbye!")
            break

        if not user_query:
            continue

        try:

            result = run_agent(
                user_query
            )

            final_report = result.get(
                "final_report",
                ""
            )

            if final_report:

                print("\n")
                print(final_report)

            else:

                print(
                    "\n⚠️ No final report was generated."
                )

        except Exception as e:

            print("\n❌ ERROR:")
            print(str(e))